export const endpointMetaSymbol = Symbol('reef:decorators:endpoint')
export const paramMetaSymbol = Symbol('reef:decorators:param')
export const controllerMetaSymbol = Symbol('reef:decorators:controller')
export const loggerMetadataKeySymbol = Symbol('reef:decorators:logger')
export const middlewareControllerKey = Symbol('reef:controller:middleware:info')
export const directMiddlewareSymbol = Symbol('reef:direct:middleware')
export const preExecutionHookSymbol = Symbol('reef:pre:execution:hook')
export const castDecoratorSymbol = Symbol('reef:cast:decorator')
